name: Renovate (OSPO) PR Events

on:
  pull_request:
    types: [opened, closed]
    branches:
      - main
      - renovate/**

jobs:
  handle-renovate-pr:
    # Run only when PR is from Renovate or OSPO Renovate
    if: |
      github.actor == 'renovate[bot]' ||
      github.actor == 'ospo-renovate[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Log Renovate PR Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo "HTML URL: ${{ github.event.pull_request.html_url }}"
      - name: When Renovate PR Opened
        if: ${{ github.event.action == 'opened' }}
        run: |
          echo "Renovate bot opened a PR: ${{ github.event.pull_request.title }}"
      - name: When Renovate PR Merged
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
        run: |
          echo "Renovate PR merged: ${{ github.event.pull_request.title }}"
